[package]
name = "pallet-contracts-uapi"
version = "4.0.0-dev"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "This crates exposes all the host functions that a contract can import"

[dependencies]
scale = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = [
	"derive",
	"max-encoded-len",
] }
cfg-if = { version = "1.0", default-features = false }
paste = { version = "1.0", default-features = false }

[features]
default = [ "std" ]
std = [ "scale/std" ]

# Enable contract debug messages via `debug_print!` and `debug_println!`.
ink-debug = []

